<a href="https://colab.research.google.com/github/tushar12345/Data-Science-Projects/blob/master/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy

[NumPy](https://numpy.org) is a powerful Python library for creating and manipulating multidimentional arrays. It has powerful functions for linear algebra, statistical analysis, and transforms.

In [0]:
import numpy as np

# Creating NumPy Arrays

NumPy arrays can be created in many ways, a few of them are shown below. The [NumPy reference](https://numpy.org/doc/1.17/reference/index.html) documents all of the [array creation](https://numpy.org/doc/1.17/reference/routines.array-creation.html) routines.

In [0]:
a = np.zeros(5)
a

In [0]:
a = np.ones(5)
a

In [0]:
np.random.random(5)

In [0]:
np.array([1, 2, 3, 4, 5])

In [0]:
np.zeros((2, 2))

In [0]:
np.random.random((2, 2))

In [0]:
np.array([[1, 2], [3, 4]])

# Basic Operations

In [0]:
a = np.ones(5)
a

In [0]:
a * 2

In [0]:
b = np.array([1, 2, 3, 4, 5])
b

In [0]:
a + b

In [0]:
# 1-D slice

b[1:4]

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
a

In [0]:
# Reverse columns

a[:, ::-1]

In [0]:
# Reverse rows

a[::-1]

In [0]:
# Rows from 1:3 and columns from 1:3

a[1:3, 1:3]

# Statistical Functions

In [5]:
a = np.array([1, 2, 3, 4, 5])

# Mean (average)

np.mean(a)

3.0

In [6]:
# Standard deviation

np.std(a)

1.4142135623730951

In [7]:
# Minimum value

np.min(a)

1

In [8]:
# Index if maximum value

np.argmax(a)

4

# Linear Algebra

In [9]:
a = 2 * np.ones(5)
b = np.array([1, 2, 3, 4, 5])

# Dot product of two vectors

a.dot(b)

30.0

In [10]:
a = np.array([[1, 2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [11]:
# Transpose of a matrix

a.T

array([[1, 3],
       [2, 4]])

In [12]:
# Determinant of a matrix

np.linalg.det(a)

-2.0000000000000004

In [13]:
# Inverse of a matrix

b = np.linalg.inv(a)
b

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [14]:
a.dot(b)

array([[1.0000000e+00, 0.0000000e+00],
       [8.8817842e-16, 1.0000000e+00]])

# Visualizing Data

[Matplotlib](https://matplotlib.org) is a powerful, easy to use plotting library. It can be used with NumPy and Pandas.

In [0]:
import math
import matplotlib.pyplot as plt

In [0]:
x = np.arange(0, 2*math.pi, 2*math.pi/50)
sin = np.sin(x)
cos = np.cos(x)

In [0]:
plt.plot(x, sin, label='sin(x)', color='blue', linewidth=2.5)
plt.plot(x, cos, label='cos(x)', color='red', linewidth=0.5)
plt.ylabel('y')
plt.xlabel('x')
plt.legend(loc='upper right')
plt.show()

In [0]:
plt.scatter(x, sin, label='sin(x)', color='green')
plt.ylabel('y')
plt.xlabel('x')
plt.legend(loc='upper right')
plt.show()

In [0]:
x = np.arange(0, math.pi, math.pi/10)
plt.bar(x, np.sin(x), align='center', width=0.2)

In [0]:
x = np.arange(0, math.pi, math.pi/10)
plt.barh(x, np.sin(x), align='center', height=0.2)

# Working with Images

NumPy and Matplotlib can be used images.

In [0]:
from skimage import io

In [0]:
h500 = io.imread('https://madhu.com/images/h500.gif')
plt.imshow(h500)

In [0]:
h500.shape

In [0]:
plt.imshow(h500[:, ::-1])

In [0]:
plt.imshow(h500[::-1])

In [0]:
plt.imshow(h500[100:200, 100:250])

# Reshaping Data

In [0]:
a = np.array([[1, 2], [3, 4]])
a

In [0]:
a.reshape(4, 1)

In [0]:
a.reshape(1, 4)

In [0]:
a.reshape(4, 1).shape

In [0]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

In [0]:
a.shape

In [0]:
a.reshape(3, 2)

In [0]:
a = np.arange(0, 6)
a

In [0]:
a.reshape(2, 3)